"use strict";

/**
 * 剪贴板与全局快捷键默认关闭。启用前不读取、不写入剪贴板，也不注册系统快捷键。
 * 不保存剪贴板历史；当前句子只交给逐词采集队列。
 */
class NativeCaptureService {
  constructor({
    clipboard,
    globalShortcut,
    sendPreview,
    intervalMs = 1200,
    accelerator,
    platform = process.platform,
  } = {}) {
    this.clipboard = clipboard;
    this.globalShortcut = globalShortcut;
    this.sendPreview = sendPreview || (() => {});
    this.intervalMs = intervalMs;
    this.platform = platform;
    this.accelerator =
      accelerator || (platform === "darwin" ? "Command+Shift+L" : "Control+Shift+L");
    this.clipboardEnabled = false;
    this.shortcutEnabled = false;
    this.timer = null;
    this.lastText = null;
    this.reads = 0;
    this.retryCount = 0;
    this.writes = 0;
    this.error = "";
    this.reading = false;
    this.generation = 0;
  }

  apply(settings = {}) {
    this.error = "";
    this.setClipboard(settings.clipboardCaptureEnabled === true);
    this.setShortcut(settings.globalShortcutEnabled === true);
  }

  setClipboard(enabled) {
    if (enabled === this.clipboardEnabled) return;
    if (!enabled) {
      this.stopClipboard();
      return;
    }
    if (!this.clipboard?.readText) throw new Error("当前环境没有可用的剪贴板接口");
    this.clipboardEnabled = true;
    this.lastText = null;
    this.timer = setInterval(() => this.poll(), this.intervalMs);
    this.timer.unref?.();
  }

  async poll() {
    return this.readPreview(false);
  }

  // 用户明确请求时只检查一次当前正文；不清空 lastText、不改变定时调度。
  async retryPreview() {
    if (!this.clipboardEnabled || this.reading) return { retried: false };
    this.retryCount++;
    return { retried: (await this.readPreview(true)) === true };
  }

  async readPreview(force) {
    if (!this.clipboardEnabled || this.reading) return false;
    this.reading = true;
    const generation = this.generation;
    this.reads += 1;
    let text = "";
    try {
      try {
        const formats = this.clipboard.availableFormats
          ? await this.clipboard.availableFormats()
          : this.clipboard.read
            ? (await this.clipboard.read()).flatMap((item) => item.types)
            : [];
        // Maccy 同样忽略密码管理器 concealed / transient / 自动生成内容；只读纯文本。
        if (formats.some((type) => /concealed|transient|autogenerated/i.test(type))) return;
        text = (await this.clipboard.readText()) || "";
        if (generation !== this.generation || !this.clipboardEnabled) return;
      } catch (error) {
        if (generation === this.generation) {
          this.error = "剪贴板读取失败";
          this.stopClipboard();
        }
        return false;
      }
      const candidate = text.trim();
      if (!candidate || (!force && candidate === this.lastText)) return false;
      // 强制仅跳过这一次的相等判断；已检查新正文仍要记住，避免拒绝后轮询再次提醒。
      this.lastText = candidate;
      const words = clipboardWords(candidate);
      if (!words.length) return false;
      await this.sendPreview({ source: "clipboard", text: candidate, words });
      return true;
    } finally {
      this.reading = false;
    }
  }

  stopClipboard() {
    this.generation++;
    const wasEnabled = this.clipboardEnabled;
    this.clipboardEnabled = false;
    if (wasEnabled) this.sendPreview({ source: "cleared" });
    if (this.timer) clearInterval(this.timer);
    this.timer = null;
    this.lastText = null;
  }

  setShortcut(enabled) {
    if (enabled === this.shortcutEnabled) return;
    if (!enabled) {
      this.stopShortcut();
      return;
    }
    if (!this.globalShortcut?.register) throw new Error("当前环境没有全局快捷键接口");
    const ok = this.globalShortcut.register(this.accelerator, () => {
      this.sendPreview({
        source: "shortcut",
        accelerator: this.accelerator,
        confirmAction: "focusCapture",
      });
    });
    if (!ok) {
      this.shortcutEnabled = false;
      this.error = "全局快捷键被其他应用占用，未启用";
      throw new Error(this.error);
    }
    this.shortcutEnabled = true;
  }

  stopShortcut() {
    // 只释放本服务注册的加速键，禁止 unregisterAll 误伤应用内其他快捷键。
    if (this.shortcutEnabled) this.globalShortcut?.unregister?.(this.accelerator);
    this.shortcutEnabled = false;
  }

  close() {
    this.stopClipboard();
    this.stopShortcut();
  }

  snapshot() {
    return {
      clipboardEnabled: this.clipboardEnabled,
      shortcutEnabled: this.shortcutEnabled,
      accelerator: this.accelerator,
      reads: this.reads,
      retryCount: this.retryCount,
      retryAvailable: this.clipboardEnabled && !this.reading,
      writes: this.writes,
      historyStored: false,
      error: this.error,
    };
  }
}

// 标点、换行和中文背景不阻断识别；URL / 邮箱不拆成无关英文词。每次最多 200 个不同词。
function clipboardWords(text) {
  if (typeof text !== "string" || text.length > 20000) return [];
  const plain = text.replace(/https?:\/\/\S+|[\w.+-]+@[\w.-]+\.[A-Za-z]+/g, " ");
  return [
    ...new Set(
      (plain.match(/[A-Za-z]+(?:['’\-][A-Za-z]+)*/g) || []).map((word) =>
        word.replaceAll("’", "'").toLowerCase(),
      ),
    ),
  ]
    .filter((word) => word.length <= 120)
    .slice(0, 200);
}
module.exports = { NativeCaptureService, clipboardWords };
